---

all:
  vars:
    ansible_user: falken
    ansible_password: "joshua"

  # host definitions
  children:
    stalingrad:
      hosts:
        10.0.1.2:
    saint-petersburg:
      hosts:
        10.0.1.3:
    moscow:
      hosts:
        10.0.1.4:
    dallas:
      hosts:
        10.0.1.5:
    chicago:
      hosts:
        10.100.1.1:

    linux:
      children:
        dallas:
        chicago:

    windows:
      children:
        stalingrad:
        saint-petersburg:
        moscow:
